// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4AF4AvMkP19rX9zLq8fDVZV7VxFLWU-k',
    appId: '1:642386240333:web:18ef3ae666d84b64d64d04',
    messagingSenderId: '642386240333',
    projectId: 'fir-kotlin-111e4',
    authDomain: 'fir-kotlin-111e4.firebaseapp.com',
    databaseURL: 'https://fir-kotlin-111e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-kotlin-111e4.appspot.com',
    measurementId: 'G-H7J61WLQZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATf7u64jgqxOPkBe2Yq4-DOnR1jzEzvzw',
    appId: '1:642386240333:android:d67e5ee4d78e6b25d64d04',
    messagingSenderId: '642386240333',
    projectId: 'fir-kotlin-111e4',
    databaseURL: 'https://fir-kotlin-111e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-kotlin-111e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHaCrKcf-PVHzpbAZ6S_YGNZfNY0SXTII',
    appId: '1:642386240333:ios:1a95c9efc3e9efc4d64d04',
    messagingSenderId: '642386240333',
    projectId: 'fir-kotlin-111e4',
    databaseURL: 'https://fir-kotlin-111e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-kotlin-111e4.appspot.com',
    iosBundleId: 'com.example.baiTap3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHaCrKcf-PVHzpbAZ6S_YGNZfNY0SXTII',
    appId: '1:642386240333:ios:22638c207f6615d3d64d04',
    messagingSenderId: '642386240333',
    projectId: 'fir-kotlin-111e4',
    databaseURL: 'https://fir-kotlin-111e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-kotlin-111e4.appspot.com',
    iosBundleId: 'com.example.baiTap3.RunnerTests',
  );
}
